<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
	<div id="wrapper">
	    <?php echo $this->getChildHtml('global_notices') ?>
		<?php echo $this->getChildHtml('global_messages') ?>
    	<div class="w1">
			<div class="w2">
				<div id="header">
					<div class="header-block">
						<ul class="main-nav">
							<li><a href="#">Blog</a></li>
							<li><a href="#">FAQ</a></li>
							<li><a href="#">Help</a></li>
						</ul>
				   		<?php echo $this->getChildHtml('header') ?>
					    <div class="bar-box">
								<a href="#">Currently Serving</a>
								<span class="calgary-text">Calgary</span>
						</div>
					</div>
					<div class="header-box">
						<strong class="logo"><a href="#">CurryBibby.com</a></strong>
						<div class="area-box">
							<a href="#" class="btn-join">JOIN CURRY BIBBY</a>
							<div class="question-box"><div class="holder"><span>What kind of curry are you cooking?</span></div></div>
							<div class="navigation">
								<div class="holder">
									<ul id="nav">
										<li><a href="#">login</a></li>
										<li><a href="#">join</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="main">
					<div class="twocolumns">
						<div class="col-info">
							<div class="holder">
								<div class="frame">
									<div class="content">
										<h1 class="text-join">Join the shareable food movement</h1>
										<p>Currybibby.com is the club that helps you buy delicious home- made food, minus the preservatives, restaurant prices, and line-ups.</p>
										<p><a href="#" class="alignleft"><img src="images/img1.gif" width="105" height="105" alt="JOIN CURRY BIBLY" /></a>Currybibby.com is perfect for foodies, students, bachelors, and time-pressed families. By joining our club you are supporting a growing and important movement. Let's take back our plates!</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-ad">
							<div class="holder">
								<div class="frame">
									<ul class="ad-box">
										<li>
											<div class="photo"><a href="#"><img src="images/img2.jpg" width="207" height="133" alt="Think you can make a mean curry?" /></a></div>
											<a href="#" class="btn-list more">LIST YOUR CURRY</a>
										</li>
										<li>
											<div class="photo"><a href="#"><img src="images/img3.jpg" width="207" height="133" alt="What's in you neighborhood?" /></a></div>
											<a href="#" class="btn-shop more">SHOP fOF CURRY</a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div id="twocolumns">
						<div id="content" class="alt-content">
							<div class="content-block">
								<div class="content-holder">
									<div class="content-frame">
											<div class="heading"><h2>Latest seller reviews</h2></div>
											<div class="reviews-box">
												<table class="reviews-holder">
													<tr class="heading">
														<th class="seller-row">Seller</th>
														<th>Spoons</th>
														<th>Chillies</th>
														<th>Curry</th>
														<th>Comments</th>
													</tr>
													<tr class="firs-row">
														<td class="seller-row"><a href="#">tinatee</a></td>
														<td class="spoons-row">
															<ul class="spoons-box">
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
															</ul>
														</td>
														<td class="chillies-row">
															<ul class="chillies-box">
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
															</ul>
														</td>
														<td class="curry-row">Kaccha kheema kofta curry</td>
														<td class="comments-box">Minim veniam quis nostrud exerci tation ullamcorper suscipit.</td>
													</tr>
													<tr>
														<td class="seller-row"><a href="#">drewbot</a></td>
														<td class="spoons-row">
															<ul class="spoons-box">
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
															</ul>
														</td>
														<td class="chillies-row">
															<ul class="chillies-box">
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
															</ul>
														</td>
														<td class="curry-row">Dahi baht</td>
														<td class="comments-box">Veniam quis nostrud exerci tation!</td>
													</tr>
													<tr>
														<td class="seller-row"><a href="#">currymonster</a></td>
														<td class="spoons-row">
															<ul class="spoons-box">
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
															</ul>
														</td>
														<td class="chillies-row">
															<ul class="chillies-box">
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
															</ul>
														</td>
														<td class="curry-row">Katsu-kare</td>
														<td class="comments-box">Exerci tation ullamcorper suscipit.</td>
													</tr>
													<tr>
														<td class="seller-row"><a href="#">viji</a></td>
														<td class="spoons-row">
															<ul class="spoons-box">
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
																<li>spoons</li>
															</ul>
														</td>
														<td class="chillies-row">
															<ul class="chillies-box">
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
															</ul>
														</td>
														<td class="curry-row">Thai green curry</td>
														<td class="comments-box">Quis nostrud exerci tation ullam corper suscipit.</td>
													</tr>
													<tr>
														<td class="seller-row"><a href="#">vishillin</a></td>
														<td class="spoons-row">
															<ul class="spoons-box">
																<li>spoons</li>
																<li>spoons</li>
															</ul>
														</td>
														<td class="chillies-row">
															<ul class="chillies-box">
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
																<li>chillies</li>
															</ul>
														</td>
														<td class="curry-row">Roghan josh</td>
														<td class="comments-box">Minim veniam quis nostrud exerci tation ullamcorper suscipit.</td>
													</tr>
												</table>
											</div>
											<div class="content-box">
												<h2>About Curry Bibby</h2>
												<p>Liber tempor cum, soluta nobis eleifend option congue! Nisl ut aliquip ex ea commodo consequat duis autem vel eum iriure dolor in hendrerit. Decima et quinta decima eodem modo typi qui nunc nobis videntur parum clari fiant sollemnes in! Quod ii legunt saepius claritas est etiam processus dynamicus qui sequitur mutationem consuetudium lectorum mirum est. Ipsum dolor sit amet consectetuer adipiscing elit sed diam nonummy. In iis qui facit eorum claritatem Investigationes demonstraverunt lectores legere.</p>
												<?php echo $this->getChildHtml('content') ?>						                        
											</div>
									</div>
								</div>
							</div>
						</div>
						<div id="sidebar">
							<div class="side-box">
								<h3 class="heading-curry">Why CURRY?</h3>
								<div class="content">
									<ul>
										<li>The word "curry" is actually an anglicised version of the Tamil word kari, meaning 'sauce'</li>
										<li>There are over 25 different distinct regions of the world that make "curry"</li>
										<li>That means hundreds of unique tastes and dishes to choose from</li>
										<li>It's easy to prepare in large quantities, to package, and freeze</li>
										<li>And it's always better the second day!</li>
									</ul>
								</div>
								<div class="more-box">
									<div class="holder"><a href="#" class="more">MORE QUESTIONS &amp; ANSWERS</a></div>
								</div>
							</div>
							<div class="side-box">
								<h3 class="heading-banner">FPO Banner</h3>
								<div class="content">
									<div class="photo"><a href="#"><img src="images/img4.gif" width="169" height="51" alt="Lorem este acerat Jacer" /></a></div>
								</div>
								<div class="more-box">
									<div class="holder"><a href="#" class="more">FIND OUT MORE</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="footer">
					<div class="add-nav">
						<div class="holder">
							<ul>
								<li><a href="#">about shareable food</a></li>
								<li><a href="#">food safety guidelines</a></li>
								<li><a href="#">privacy policy</a></li>
								<li><a href="#">currybibby needs translators!</a></li>
								<li><a href="#">make a suggestion</a></li>
							</ul>
						    <?php echo $this->getChildHtml('footer') ?>
					        <?php echo $this->getChildHtml('before_body_end') ?>	    
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>